package generator

var namaJalan = []string{
	"Jln. Teuku Panglima Polem",
	"Jln. Tuwanku Muhammad Daudsyah",
	"Jln. Jend. A. Yani Kec. Kuta Alam",
	"Jln. Pocut Baren Kec. Kuta Alam",
	"Jln. Syiah Kuala Kec. Kuta Alam",
	"Jln. Khairil Anwar",
	"Jln. Sisingamangaraja",
	"Jln. Tuwanku Hasyim Banta Muda",
	"Jln. H. Dimurtala",
	"Jln. T. Chik Kuta Karang",
	"Jln. T. Malem I",
	"Jln. T. Malem II",
	"Jln. T. Malem III",
	"Jln. Study Fond",
	"Jln. Potemerehom",
	"Jln. St. Al - Kahar Kel. Kuta Alam",
	"Jln. Perkasa Alam",
	"Jln. Puda",
	"Jln. Sentosa",
	"Jln. Al-Huda",
	"Jln. Perdamaian ",
	"Jln. Bakti",
	"Jln. Muskana Kp. Laksana Kec. Kuta Alam",
	"Jln. Letnan",
	"Jln. Maimun Saleh Kel. Mulia Kec. Kuta Alam",
	"Jln. Pocut Meurah Inseun",
	"Jln. Tgk. Cik Tanoh Abee",
	"Jln. T. Hasan Dek",
	"Jln. Tgk. Chik Kuta Karang Kuta Alam",
	"Jln. Tgk. Malem Muda Kec. Kuta Alam",
	"Jln. Fakinah Kel. Mulia",
	"Jln. T. Laksamana",
	"Jln. Tgk. Diblang Kec. Kuta Alam",
	"Jln. Merpati Raya",
	"Jln. Kaswari",
	"Jln. Teladan",
	"Jln. Bangau",
	"Jln. Pati Kel Keuramat",
	"Jln. Pelangi",
	"Jln. T. Teungoh",
	"Jln. Supratman",
	"Jln. Syech Mohd. Yamin",
	"Jln. Teluk Betung",
	"Jln. Kartini Kec. Kuta Alam",
	"Jln. Jambi",
	"Jln.  Kec. Kuta Alam",
	"Jln. H.T. Daudsyah",
	"Jln. Prof. Dr. Syarif Thayeb",
	"Jln. Tgk. Di Anjong",
	"Jln. Tgk. Di Kandang",
	"Jln. Tgk. Muda",
	"Jln. Malem Dagang",
	"Jln. Ayah Gani Kec. Bandar Baru",
	"Jln. Chik Mohd. Thayeb Peureulak",
	"Jln. Ayah Hamid",
	"Jln. Pari",
	"Jln. Cumi-Cumi",
	"Jln. Todak",
	"Jln. Senangin",
	"Jln. Tenggiri",
	"Jln. Gurami",
	"Jln. Sepat",
	"Jln. Bawal",
	"Jln. Bandeng",
	"Jln. Mujair",
	"Jln. Salam",
	"Jln. Tanggul (Taman Ratu Safiatuddin)",
	"Jln. Lumba-Lumba",
	"Jln. Kartika Kec. Kuta Alam",
	"Jln. Panglima Nyak Makam",
	"Jln. Tgk. Chik Indrapuri",
	"Jln. Tgk. Teupin Raya",
	"Jln. Tgk. Di Bitai",
	"Jln. Tgk. Cot Plieng",
	"Jln. Bintara Pineung",
	"Jln. Tgk. Lam Oe Kec. Kuta Alam",
	"Jln. Panglima Lamreh",
	"Jln. Malikul Saleh I",
	"Jln. Malikul Saleh II",
	"Jln. Malikul Saleh III",
	"Jln. Nirbaya",
	"Jln. Kuwera I Kec. Kuta Alam",
	"Jln. Sultan Alaidin Johansyah",
	"Jln. Tongkol",
	"Jln. Tgk. Abdullah Ujong Rimba",
	"Jln. Prof A. Majid Ibrahim I",
	"Jln. Prof A. Majid Ibrahim Ii",
	"Jln. Syeh Muda Wali",
	"Jln. Imam Bonjol",
	"Jln. K. H. A. Dahlan - Sp. Diponegoro Baiturr.",
	"Jln. Tentara Pelajar ",
	"Jln. Mohd. Jam",
	"Jln. Blang Padang",
	"Jln. Tgk. Pulau Dibaroh",
	"Jln. Cemara Kec. Baiturrahman",
	"Jln. T. Cut Ali",
	"Jln. Sabang",
	"Jln. Amandimot",
	"Jln. Idi Kec. Baiturrahman",
	"Jln. Tgk. Chik Pante Kulu",
	"Jln. Diponegoro",
	"Jln. Teratai",
	"Jln. Cut Mutia Kec. Kuta Raja",
	"Jln. Tepi Kali Kec Baiturrahman",
	"Jln. Inpres",
	"Jln. Perwira",
	"Jln. Syeh Mohd. Saman",
	"Jln. Sultan Mansursyah",
	"Jln. Taman Makam Pahlawan",
	"Jln. Amaliah",
	"Jln. Nyak Adam Kamil I Kec. Baiturrahman",
	"Jln. Nyak Adam Kamil Ii Kec. Baiturrahman",
	"Jln. Nyak Adam Kamil Iii Kec. Baiturrahman",
	"Jln. Nyak Adam Kamil Iv Kec. Baiturrahman",
	"Jln. Tgk. Sulaiman Daud",
	"Jln. Utama ",
	"Jln. Merpati Kel. A. Pahlawan",
	"Jln. Singgah Mata Kec. Baiturrahman",
	"Jln. Pattimura Kec. Baiturrahman",
	"Jln. Merapi Singgalang",
	"Jln. Tuwanku Abdul Aziz",
	"Jln. St. Johan Merduati",
	"Jln. Panglateh",
	"Jln. Taman Siswa Kec. Kuta Raja",
	"Jln. Tuwanku Raja Keumala",
	"Jln. Pocut Meurah",
	"Jln. Habib Abd. Rahman",
	"Jln. Induk Desa Sukadamai",
	"Jln. Angsa",
	"Jln. Singgalang ",
	"Jln. Rawa Sakti Barat",
	"Jln. Rawa Sakti Timur",
	"Jln. Rawa Sakti I",
	"Jln. Rawa Sakti Ii",
	"Jln. Rawa Sakti Iii",
	"Jln. Rawa Sakti Iv",
	"Jln. Rawa Sakti V",
	"Jln. Rawa Sakti Vi",
	"Jln. Rawa Sakti Vii",
	"Jln. Rawa Sakti Viii",
	"Jln. Rawa Sakti Ix",
	"Jln. Sp. T.P. Nyak Makam -Ds. Ie Masen Kayee Adang",
	"Jln. Akasia",
	"Jln. Kenari Prada",
	"Jln. Cendana",
	"Jln. Delima",
	"Jln. Jambu",
	"Jln. Durian Kec. Baiturrahman",
	"Jln. Flamboyan Prada",
	"Jln. Meulu",
	"Jln. Anggrek Prada",
	"Jln. Cempaka Kel. Punge Jurong Meuraxa",
	"Jln. Seulanga",
	"Jln. Seroja",
	"Jln. Kelapa",
	"Jln. Anggur",
	"Jln. Beringin Prada Utama",
	"Jln. Lampaseh Kota -Ulee Lheu",
	"Jln. Perintis Kel. Punge Jurong Meuraxa",
	"Jln. Perdamaian",
	"Jln. Bakti ",
	"Jln. Syahmidin",
	"Jln. Persatuan",
	"Jln. Tgk. Abd. Rahman Meunasah Meucap",
	"Jln. Fatahillah",
	"Jln. Rawa Sakti",
	"Jln. Wedana Kec. Banda Raya",
	"Jln. Hasan Saleh",
	"Jln. Fatahillah I",
	"Jln. Pante Cermin",
	"Jln. Pemancar",
	"Jln. Mancang",
	"Jln. Elang",
	"Jln. Sarong Keris Ds. Panterik Lueng Bata",
	"Jln. Stadion H. Dimurthala",
	"Jln. Ujong Batee",
	"Jln. Taman Sari Baru",
	"Jln. Kerinci",
	"Jln. Tgk. Hasan Krueng Kale Baiturrahman",
	"Jln. Keuchik Saman",
	"Jln. Keuchik Amin Kel. Beurawe",
	"Jln. Nuri",
	"Jln. Kasturi",
	"Jln. Tgk. Chiek Dipineung Iv",
	"Jln. Kuwera Ii",
	"Jln. Tuan Di Banda",
	"Jln. Kuta Manyang",
	"Jln. Tgk. Cik. Pineung Vi",
	"Jln. Mujahidin",
	"Jln. Sri Ratu Safiatuddin",
	"Jln. Melati",
	"Jln. Anggrek Punge Jurong",
	"Jln. Tulip",
	"Jln. Teratai Keudah",
	"Jln. Seroja",
	"Jln. Suri",
	"Jln. Kandang XII",
	"Jln. Durian",
	"Jln. Neusu Aceh (Bakti - Rambong)",
	"Jln. T.A. Samaun Lueng Bata",
	"Jln. Mujur",
	"Jln. Krueng Tripa",
	"Jln. Krueng Simpo",
	"Jln. Krueng Daroy",
	"Jln. Krueng Peusangan",
	"Jln. Krueng Wayla",
	"Jln. Mesjid Al-Qurban",
	"Jln. Tgk. Cik. Dipineung Vii",
	"Jln. Ara Kundo",
	"Jln. Kesatria",
	"Jln. Purnawirawan",
	"Jln. Glee Pulot",
	"Jln. Geurute",
	"Jln. Putri Hijau",
	"Jln. Ulee Kareung - Lamgapang",
	"Jln. Japakeh",
	"Jln. Meurak Desa Suka Damai",
	"Jln. Ismail",
	"Jln. Beringin Cot Mesjid",
	"Jln. Cempaka Putih",
	"Jln. Cot Makmum",
	"Jln. Kamboja",
	"Jln. Ie Masen Kayee Adang-Ds. Doi",
	"Jln. Banda Jaya",
	"Jln. Kenari Lampulo",
	"Jln. Tgk. Chik Dipineung Viii",
	"Jln. Tanah Tinggi",
	"Jln. Bahagia",
	"Jln. Paya Lhok",
	"Jln. Mini Jaya",
	"Jln. Setia",
	"Jln. Cakra",
	"Jln. H. Abu Bakar",
	"Jln. Dipo",
	"Jln. Paya Umet",
	"Jln. G. Marabunta",
	"Jln. G. Keumala",
	"Jln. Cot Jeumpa",
	"Jln. Glee Bruek",
	"Jln. Paro I",
	"Jln. Paro II",
	"Jln. Pnka I",
	"Jln. Pnka II",
	"Jln. Belibis Kec. Baiturrahman",
	"Jln. Langgar",
	"Jln. Amrin",
	"Jln. Tgk. Chik Lampaloh",
	"Jln. Kutilang Kec. Lueng Bata",
	"Jln. Kiwi Ds. Induk Sukadamai Lueng Bata",
	"Jln. Jatu",
	"Jln. Tgk. Husein Ds. Jeulingke Kec. Syiah Kuala",
	"Jln. Rawa Setia",
	"Jln. Padat Karya Pango",
	"Jln. Manunggal XlI Kec. Lueng Bata (AMD)",
	"Jln. Tgk. Ismail",
	"Jln. Cendrawasih Kel. Keuramat ",
	"Jln. Rumoh Aceh",
	"Jln. Kenari Kel Keuramat",
	"Jln. Utoh Saman",
	"Jln. Diwai Makam",
	"Jln. Tgk. Munira",
	"Jln. Tgk Chik Lamdom (Lampreh)",
	"Jln. Rajawali",
	"Jln. Balee",
	"Jln. Utama",
	"Jln. Tgk. Zainal Abidin Makam",
	"Jln. Bilal",
	"Jln. Cot Aron",
	"Jln. Sultan Malikul Saleh",
	"Jln. Residen Danubroto Kec. Banda Raya",
	"Jln. Keuchik H. Jalil",
	"Jln. Tgk. Pineung Iii",
	"Jln. Tgk. Pineung Ii",
	"Jln. Tgk. Pineung I",
	"Jln. Tgk. Pineung Ix",
	"Jln. Tgk. Dipineung Teungoh",
	"Jln. Peulangan",
	"Jln. G. Kulu",
	"Jln. Mesjid Istiqamah",
	"Jln. Gerdong",
	"Jln. Gle. Jeudah",
	"Jln. Tuan Digaca",
	"Jln. Menasah Guci",
	"Jln. Cempaka",
	"Jln. Blang Cut",
	"Jln. Kakap Kel. Laksana Kec. Kuta Alam",
	"Jln. Nusa Indah Punge",
	"Jln. K. Nago Lampaseh",
	"Jln. Harapan Punge Blang Cut",
	"Jln. Himalaya",
	"Jln. Tanjung Utama",
	"Jln. G. Lauser",
	"Jln. Kulu I",
	"Jln. Gle Gurah",
	"Jln. Jeudah",
	"Jln. Cut A. Jalil",
	"Jln. Raja Si Uro",
	"Jln. Bahtera",
	"Jln. Bangka Rukoh",
	"Jln. Bangka Keudah",
	"Jln. Keumuning Merduati Kec. Kuta Raja",
	"Jln. Tgk. Hanafiah Deah Baro",
	"Jln. Tgk. Dikuta Lamdingin",
	"Jln. Rukun Sentosa",
	"Jln. Batee Timoh Lingke",
	"Jln. Tgk. Umar Bathoh",
	"Jln. Tanjung Utama",
	"Jln. Rukun Abadi",
	"Jln. Sekawan",
	"Jln. Beringin I Cot Mesjid",
	"Jln. Al Habsyi",
	"Jln. Bahagia Batoh",
	"Jln. Batara Cot Mesjid",
	"Jln. Perumahan Pemda Neusu",
	"Jln. Makmur",
	"Jln. Tgk. Direleng",
	"Jln. Langgar",
	"Jln. Mulia Neusu Jaya",
	"Jln. Adam",
	"Jln. Enau",
	"Jln. Mesjid Punge Ujong",
	"Jln. Sp. Beurawe-Pango Kec. Ulee Kareng",
	"Jln. Usman Lampaloh",
	"Jln. Pusara Lingke",
	"Jln. Bahagia Mulia",
	"Jln. Keuchik Man Neusu Jaya",
	"Jln. Manunggal",
	"Jln. Tgk. Chik Panterik",
	"Jln. Apel Lueng Bata",
	"Jln, Tgk. Chik Gempa",
	"Jln. Pang. Mak Hasan",
	"Jln. Tgk. Rayek",
	"Jln. Tgk. Diaji",
	"Jln. Kenanga Ds. Lampulo Kec. Kuta Alam",
	"Jln. Ujong Blang Mulia",
	"Jln. Agraria",
	"Jln. Balam",
	"Jln. Puskesmas Lambhuk",
	"Jln. Blang Cut",
	"Jln. Tgk. Pineung",
	"Jln. Cut Saman",
	"Jln. Sp. Propinsi-Kp. Pie",
	"Jln. Melati Mibo",
	"Jln. Perumahan Guru Mibo",
	"Jln. Kemuning",
	"Jln. Taman Karya",
	"Jln. Pemancar Dalam",
	"Jln. Pepabri",
	"Jln. Stadion Harapan Bangsa",
	"Jln. Kuta Baro",
	"Jln. Kuta Raja",
	"Jln. Blang Pie",
	"Jln. Mns. Nie",
	"Jln. Alue Deah Tengoh",
	"Jln. Pintu Air Lampaseh Kuta",
	"Jln. Nek Tok",
	"Jln. Sikawek Ds. Cot Lamkeuweh Meuraxa",
	"Jln. Bakti Geuce ",
	"Jln. Aneuk Galong",
	"Jln. Cot Jambe",
	"Jln. Merpati Raya",
	"Jln. Fatahillah Iv",
	"Jln. Fatahillah I",
	"Jln. Meuraksani",
	"Jln. Tgk. Meunara",
	"Jln. Sudirman I",
	"Jln. Sudirman II",
	"Jln. Tgk. Chik Panteriek",
	"Jln. Jakalam",
	"Jln. Batee Timoh",
	"Jln. Lam Awe",
	"Jln. Cendawan",
	"Jln. Mesjid Lamjabat",
	"Jln. Sp. Propinsi-Lamjame",
	"Jln. Gp. Blang-Lam Beude",
	"Jln. Tunggal I",
	"Jln. Tunggal II",
	"Jln. Salihin",
	"Jln. Babul Jannah-T. Samidan",
	"Jln. Tgk. Jusuf",
	"Jln. Lee Guna",
	"Jln. Pusara Habib",
	"Jln. K. Rahman",
	"Jln. Mesjid Tuha",
	"Jln. Mesjid Ulee Kareng",
	"Jln. Seroja Ie Masen",
	"Jln. Arifin Ahmad",
	"Jln. Kebun Baru",
	"Jln. Tanjung",
	"Jln. Jeumpa",
	"Jln. Bakti",
	"Jln. Ikhsan ",
	"Jln. Kapai Kleng",
	"Jln. Rukun Damai Utama",
	"Jln. Meunasah Kuta",
	"Jln. Utuh Muslimin",
	"Jln. Tandi",
	"Jln. Kepiting",
	"Jln. Sp. Prada-Sp. Tgk. Lamgugop",
	"Jln. Mutiara",
	"Jln. Belimbing",
	"Jln. Kasturi Lamgugop",
	"Jln. Putri Meurendan Dewi",
	"Jln. Budaya",
	"Jln. Tgk. Meurah",
	"Jln. Lhok Bangka",
	"Jln. Sp. Mesjid Babul Taqwa-Jeulingke",
	"Jln. Syiah Kuala-Perumahan Koperasi",
	"Jln. Kamboja Lampulo",
	"Jln. Indra Budiman",
	"Jln. Sp. Jembatan Lamnyong-Alue Naga",
	"Jln. Sp. Kr. Cut-Syiah Kuala",
	"Jln. Alue Naga I",
	"Jln. Alue Naga Ii",
	"Jln. Alue Naga Iii",
	"Jln. Alue Naga Iv",
	"Jln. Poteumerehom I",
	"Jln. Kuala Batee",
	"Jln. Kuta Meugah",
	"Jln. Bahagia Lamlagang",
	"Jln. Lampoh Raya",
	"Jln. Tgk. Mohd. Hasan",
	"Jln. Tgk. Saman Lueng Bata",
	"Jln. Perjuangan Blang Cut",
	"Jln. Flamboyan Lampulo",
	"Jln. Peudaya Keuramat",
	"Jln. Tgk. Bunthok Beurawe",
	"Jln. Unida Surien",
	"Jln. Langsat",
	"Jln. Mancang, Jln. Geupang, Jln. Jambu",
	"Jln. Nangka",
	"Jln. Dusun Mesjid",
	"Jln. Rambutan",
	"Jln. Ds. Kehakiman, Ds. Remaja",
	"Jln. Manggis",
	"Jln. Pepaya",
	"Jln. Mon Nibong & Lampoh Kua",
	"Jln. Monja",
	"Jln. Syarif & Jln. Tuan Ceukok",
	"Jln. Ateung Tuha",
	"Jln. Lembah Hijau",
	"Jln. Lamthu",
	"Jln. Lhok Pintah",
	"Jln. T. Mae",
	"Jln. Batoh Jembatan",
	"Jln. Mini Jaya",
	"Lr. Serambi Mekkah",
	"Jln. Mutia",
	"Jln. Jerat Mudar/Cot Kelayu",
	"Jln. Kenari",
	"Jln. Gelatik",
	"Jln. Angsa",
	"Jln. Beo",
	"Jln. Rencong Aceh",
	"Jln. Desa Mas Murni",
	"Jln. Cut Apa Maein",
	"Jln. T. M. Saman",
	"Jln. T. Ali",
	"Lr. T. Chik Panterik",
	"Jln. Aulia Mujahhirin",
	"Jln. Payong Patoe & Ke Komp. Mibo",
	"Jln. Blang Kulat",
	"Jln. Geuceu Menara Vi",
	"Jln. Mangga",
	"Jln. Anggrek",
	"Jln. Durian",
	"Jln. Manggis",
	"Jln. Tembaga",
	"Jln. Bahagia",
	"Jln. Saudara",
	"Jln. Sekawan",
	"Jln. Sahabat",
	"Jln. Selamat",
	"Jln. Muskana",
	"Jln. Sejahtera",
	"Jln. Mawar",
	"Jln. Tongkol",
	"Jln. Teman",
	"Jln. Besi",
	"Jln. Emas",
	"Jln. Kerawang",
	"Jln. Siyung-Yung",
	"Jln. T. Teungoh",
	"Jln. Anggrek",
	"Jln. Beringin Ii",
	"Jln. Meulur/Kenaga",
	"Jln. Cempaka",
	"Jln. Kamboja",
	"Jln. Beringin I",
	"Jln. Dahlia",
	"Jln. Keladi",
	"Jln. Matahari",
	"Jln. Seroja I & Ii",
	"Jln. Melati",
	"Jln. Kaswari",
	"Jln. Tulip",
	"Jln. Mawar Ii",
	"Jln. Buah Delima",
	"Jln. Lauser",
	"Jln. Nusa Indah",
	"Jln. Bangka Delima",
	"Jln. Aspol Airud",
	"Jln. Tepi Alur",
	"Lr. Seulanga",
	"Lr. Ujung Blang",
	"Lr. Bak Asan",
	"Lr. Nyak Awan",
	"Lr. Tgk. Imum",
	"Lr. Buntu",
	"Lr. Tgk. Ismail",
	"Lr. Cut Saman",
	"Lr. Bransyah",
	"Lr. Nyak Jaksan",
	"Lr. Tgk. Di Gano",
	"Lr. Mushalla/Gano",
	"Jln. Anggur",
	"Jln. Semangka",
	"Jln. Beringin",
	"Jln. Kelapa",
	"Jln. Cermai",
	"Jln. Bak Panah",
	"Jln. Durian 1 S/D 4",
	"Jln. Kepula",
	"Jln. Apel",
	"Jln. Setapak",
	"Jln. Makmur",
	"Jln. Tembus Glumpang Diwai Makam",
	"Jln. Keuchik Gam",
	"Jln. T. Iskandara Muda, Gg. T. Lampanah",
	"Jln. K. Amin",
	"Jln. Chik Gempa Ii",
	"Jln. Panglima Hasan",
	"Jln. Toe Pineung",
	"Jln. Krueng Blang",
	"Jln. Jeurat Raya",
	"Jln. T. A. Rahman",
	"Jln. Ie Saman Gg. Lampoh Lhok",
	"Jln. Nirbaya Ii",
	"Jln. Belanak",
	"Jln. Kepiting",
	"Jln. Kakap I",
	"Jln. Kakap Ii",
	"Jln. Kakap Iii",
	"Jln. Kakap Iv",
	"Jln. Al Ikhlas",
	"Jln. Setia",
	"Jln. Nuri",
	"Jln. Cendrawasih",
	"Jln. Taqwa",
	"Jln. Kasturi",
	"Jln. Tanah Tinggi",
	"Jln. Kedidi",
	"Jln. Balam",
	"Jln. Suri",
	"Jln. Sentosa",
	"Jln. Rahawali",
	"Jln. T. Mansur",
	"Jln. Pinggir Sungai",
	"Lr. Jambu - Lr. Pustaka Esa",
	"Jln. Imalaya",
	"Lr. Barona",
	"Lr. Pt. Burung Laut",
	"Lr. Pt. Anak Laut",
	"Lr. Los Pisang",
	"Jln. Tanoh Abee Ii",
	"Jln. Tgk. Dilepu",
	"Jln. Ujong Blang",
	"Jln. Kuala Unga",
	"Jln. Kuala Bate",
	"Jln. Tgk. Mengat",
	"Jln. Tgk. Tanoh Abee",
	"Jln. Aneuk Galong",
	"Jln. Agraria",
	"Jln. Mutiara",
	"Jln. Berlian",
	"Jln. Bahtera",
	"Lr. Mesjid",
	"Jln. Permata",
	"Jln. Gajah",
	"Jln. Tanggul",
	"Jln. Mutiara",
	"Jln. Meusara",
	"Jln. Sepakat I",
	"Jln. Amal Ii",
	"Lr. Tgk. Tengoh",
	"Jln. Lam Awe",
	"Jln. Kuburan",
	"Jln. Cendana",
	"Jln. Perdamaian",
	"Lr. Lampoh Daya",
	"Jln. Cut Abi",
	"Jln. Munira",
	"Jln. Tuan Di Kaca",
	"Jln. Dahlia",
	"Jln. Cempaka",
	"Jln. Baru",
	"Jln. Taman Bahagia",
	"Jln. Keramik",
	"Jln. Gle Bruek",
	"Jln. Genteng",
	"Jln. Leuser",
	"Jln. Pang Raed",
	"Jln. Arifin Ahmad",
	"Komp. Laksus",
	"Jln. Bakti",
	"Jln. Sawah I",
	"Jln. Sawah Ii",
	"Jln. Kreung Doi",
	"Jln. Ke Kuburan Umum",
	"Jln. Seruni",
	"Jln. Jambe Kleng",
	"Jln. Serumee",
	"Jln. Bak Hasan",
	"Jln. Pokat",
	"Jln. Seroja",
	"Jln. Kecil Sa'ad",
	"Jln. Tgk. H. M. Husen",
	"Jln. Tgk. Ishak",
	"Jln. Dusun Mawar",
	"Jln. Flamboyan",
	"Jln. Nagasari",
	"Jln. Abdul Kadir",
	"Jln. Sawah",
	"Jln. Cot Mae",
	"Jln. Komp. Perumnas",
	"Jln. Lem Saleh",
	"Jln. Dusun Damai",
	"Jln. Meunasah",
	"Jln. Dusun Deah Alue",
	"Jln. Meunasah Nibong",
	"Jln. T. Husen",
	"Jln. Cut Ali",
	"Jln. Belimbing",
	"Jln. T. Cot. Bak Beum Ii",
	"Jln. T. Cot. Bak Beum Iii",
	"Jln. T. Idris",
	"Jln. T. Makam",
	"Jln. T. Harun",
	"Jln. Perbatasan Desa",
	"Jln. Tgk. Abd. Ali",
	"Jln. Habi",
	"Jln. Utoh Musa",
	"Jln. Komp. Perumnas Pt. Pos",
	"Jln. Toke Insya",
	"Jl. Rubia",
	"Jln. Meunasah Tuha/K. Rahman",
	"Jln. Usman Sagop",
	"Jln. Tgk. Yusuf",
	"Jln. Abu Solong",
	"Jln. Bintang I ",
	"Jln. Bintang Ii",
	"Jln. Tgk. Mohd. Tuha",
	"Jln. Pusara Ahdi",
	"Jln. Leguna I",
	"Jln. K. Saman",
	"Jln. Tgk. Direuleng",
	"Jln. Bak Lipe",
	"Jln. Meunasah Bak Mee",
	"Jln. Tgk. Ben",
	"Jln. Blang Paseh",
	"Jln. Mawar",
	"Jln. Tgk. Saleh",
	"Jln. Ketimil",
	"Jln. Sentosa",
	"Jln. Yahya Geh",
	"Jln. Keluarga",
	"Jln. Malahayati",
	"Jln. Pesantren Simpang Mesjid Pango",
	"Jln. Makmur",
	"Jln. Tgk. Ahmad",
	"Jln. Tgk. H. Abas",
	"Jln. Tgk. Musa",
	"Jln. Meulu I",
	"Jln. Meulu Ii",
	"Jln. Melati",
	"Jln. Meulu",
	"Jln. Kuburan",
	"Jln. Chik Rayek",
	"Jln. Kelinci I",
	"Jln. Kelinci Ii",
	"Jln. Gg. Rahmani",
	"Jln. Bayem",
	"Jln. Utama, Jln. Kuta Rentang Tembus Ke Desa Alue Naga",
	"Jln. Tgk. Meulagu & Jln. Mesjid (Baru)",
	"Jln. Tgk. Chik Pineung Vii",
	"Jln. Rukun Sejahtera",
	"Jln. Tgk. Chik Pineung Xvii",
	"Jln. Tgk. Chik Pineung Ix",
	"Jln. Rukun Damai",
	"Jln. Tgk. Chik Pineung Iii",
	"Jln. Sentosa",
	"Jln. T. B. Pineung",
	"Jln. T. M. Rayeuk",
	"Jln. R. Warisan",
	"Jln. Prada Utama Lr Keutapang Wangi",
	"Jln. Prada Utama Lr Tgk. Cut",
	"Jln. Prada Utama Lr Tunggai I",
	"Jln. Prada Utama Lr. Benang Coklat",
	"Jln. Pang Pango",
	"Jln. Tgk. Muda",
	"Jln. Bak Geulupe",
	"Jln. Beringin Ii & Iii",
	"Jln. Jeumpa",
	"Jln. Suhada",
	"Jln. Pang Ulee Baloek",
	"Jln. Tgk Batee Timoh",
	"Gg. Kupula",
	"Jln. Meulu & Jln. Kupula",
	"Jln. Selanga & Jl Serune",
	"Jln. Dusun Barat",
	"Jln. Jeumpa",
	"Jln. Asam Manis",
	"Jln. Cot Bak U",
	"Jln. Dusun Beunot",
	"Jln. Dusun Musafir",
	"Jln. Dusun Kutaran",
	"Jln. Dusun Po Diaman",
	"Jln. Dusun Lam Ara",
	"Jln. Mesjid Tembus Jln. Lingkar Kampus",
	"Jln. Mesjid Sd/Min",
	"Jln. Daud Silang",
	"Jln. Remaja Harapan Rukoh",
	"Jln. Durian Desa Kayee Adang",
	"Jln. Flamboyan",
	"Jln. Tk. Percontohan Al Azhar Lam Gugob",
	"Jln. T. Iskandar",
	"Jl. Adam (Kec. BR)",
	"Jl. Melati (Kec. BR)",
	"Jl. Enau (Kec. BR)",
	"Jl. SDLB Kel. Ateuk Pahlawan (Kec. BR)",
	"Jl. Belibis Labui A. Pahlawan (Kec. BR)",
	"Jl. MIN Mesjid Raya. Kel. A. Pahlawan (Kec. BR)",
	"Jl. Langgar Ateuk Dayah Tanoh (Kec. BR)",
	"Jl. Rumoh Aceh Kel. Peuniti (Kec. BR)",
	"Jl. Mulia Neusu Jaya (Kec. BR)",
	"Jl. Bahagia Neusu Jaya (Kec. BR)",
	"Jl. Lingk. Makmur Neusu Jaya (Kec. BR)",
	"Jl. Bahagia Desa Ateuk Jawo (Kec. BR)",
	"Jl. Balai Desa/Langgar A. Munjeng (Kec. BR)",
	"Jl. Pasantren A. Jawo (Kec. BR)",
	"Jl. Mesjid Taqwa Setui (Kec. BR)",
	"Jl. Pemancar Dalam II (Kec. BR)",
	"Jl. Pemancar Dalam III (Kec. BR)",
	"Jl. Idi (Kec. BR)",
	"Jl. Multatuli (Kec. BR)",
	"Jl. Cemara",
	"Jl. Sentosa (Kec. KA)",
	"Jl. Tgk. Malem I (Kec. KA)",
	"Jl. Keunanga & Jl. Seurune Ds. Lampulo (Kec. KA)",
	"Jl. Kompl. Asrama Pamen Polri Kel. Kt. Alam (Kec. KA)",
	"Jl. Gajah Kuta Alam (Kec. KA)",
	"Jl. Malikul Saleh I",
	"Jl. Malikul Saleh II",
	"Jl. Malikul Saleh III",
	"Jl. Saudara (Kec. KA)",
	"Jl. Bahagia (Kec. KA)",
	"Jl. Lumba - Lumba",
	"Jl. Nirbaya II",
	"Jl. Mujair",
	"Jl. Kuwera",
	"Jl. Seulanga",
	"Jl. K. Amin",
	"Jl. Cut mahmum (Samping PLN)",
	"Jl. Cut mahmum (ujung T. Iskandar)",
	"Jl. Tgk. Ahmad",
	"Jl. Pasar pagi Beurawe",
	"Jl. Pelangi (Kec. KA)",
	"Jl. Kuwera I (Kec. KA)",
	"Jl. Indra Budiman (Lampulo)",
	"Jl. Kakap",
	"Jl. Hiu",
	"Jl. Tongkol",
	"Jl. Sabu",
	"Jl. Kepiting",
	"Jl. Udang",
	"Jl. Lestari",
	"Jl. Buntu",
	"Jl. Pang Sago",
	"Jl. Baru",
	"Jl. Kadus",
	"Jl. Tgk. Adi",
	"Jl. Abu Lampulo",
	"Jl. Pak Wan",
	"Jl. Utama",
	"Jl. Bahagia I",
	"Jl. Bahagia II",
	"Lr. Puyuh",
	"Jl. Setia",
	"Jl. Tanah Tinggi",
	"Jl. Melati",
	"Jl. Taqwa",
	"Jl. Keudidi",
	"Jl. Rajawali",
	"Lr. Al - Ikhlas",
	"Lr. Berlian",
	"Lr. Buntu (Samping Jl. Perdamaian)",
	"Jl. Anggur (Lambaro Skep)",
	"Jl. Bak Panah I",
	"Jl. Permai",
	"Jl. Bak Panah II",
	"Jl. Bahtera I Buntu",
	"Jl. Bahtera II Buntu",
	"Jl. Kuta Karang Buntu",
	"Jl. Kuta BateeII Buntu",
	"Jl. Kuta Batee II Buntu",
	"Jl. Aneuk galong III",
	"Jl. Kuta Batee III Buntu I",
	"Jl. Kuta Batee III",
	"Lr. Buntu Jl. Tgk. Diblang (Kp. Mulia B)",
	"Jl. Malahayati",
	"Jl. Intan",
	"Jl. Permata",
	"Jl. Berlian",
	"Lr. Buntu Jl. Permata",
	"Jl. T. Rani (Kel. Mulia Lr. 3 & 4)",
	"Jl. Metro",
	"Jl. Sukon",
	"Jl. Aneuk Galong - 1",
	"Jl. Aneuk Galong  - 2",
	"Jl. Mnr Inseun",
	"Jl. Kuta Krueng",
	"Jl. Malem Mudah - I",
	"Jl. Fakinah",
	"Jl. Malem Mudah - II",
	"Jl. Kuala Bate",
	"Jl. Buntu ( Samping Jl. P. Polem)",
	"Jl. T. Laksamana",
	"Jl. Kuta Lampanah - I",
	"Jl. T. Wahab",
	"Jl. Kuta Lampanah - II",
	"Lr. Jl. Sisinga Maharaja",
	"Jl. Mawar (Kp. Laksana A)",
	"Jl. Buntu",
	"Jl. Anggrek",
	"Jl. Bakti",
	"Jl. Saudara",
	"Jl. Teman",
	"Jl. Samanalagi",
	"Jl. Sahabat",
	"Jl. Mesjid",
	"Jl. Emas",
	"Jl. Nagan",
	"Jl. Intan",
	"Jl. Pinggir Kali Ling. Unta Belakang Asrama Kuta Alam",
	"Jl. Salihin Lamglumpang Ulee Kareng (Kec. UK)",
	"Jl. Tgk. Muhammad Tuha Cirih (Kec. UK)",
	"Jl. Leguna I & II Cirih (Kec. UK)",
	"Jl. Utama Ie Masen Ulee Kareng",
	"Jl. Rayeuk Utama Ie Masen Ulee Kareng",
	"Jl. Tgk. Makam Desa Doy",
	"Jl. Akses Komplek Perkantoran dan Rumah Sakit",
	"Jl. masuk belakang SMP Neg. 19 Percontohan",
	"Jl. Raja Jalil Desa Lamlagang (Kec. BNR)",
	"Jl. Melati Desa Lamlagang (Kec. BNR)",
	"Jl. Seulanga Desa Lamlagang (Kec. BNR)",
	"Jl. Bandung Desa Geuce Kayee Jatho (Kec. BNR)",
	"Jl. Semarang Desa Geuce Kayee Jatho  (Kec. BNR)",
	"Jl. Solo Desa Geuce Kayee Jatho (Kec. BNR)",
	"Jl. Kesehatan Desa Kayee Jatho (Kec. BNR)",
	"Jl. Peulangan-Lhoong Cut Kec.Banda Raya ",
	"Jl. Lorong Melur Lhong Raya Kec. Banda Raya",
	"Jl. Lorong Buntu Lam Ara Kec. Banda Raya",
	"Jl. Perumahan Guru Desa Mibo Kec. Banda Raya",
	"Jl. Teratai II Lhong Raya Kec. Banda Raya",
	"Jl. Muktamar",
	"Jl. Tanggul Kp. Penyeurat",
	"Jl. Kuburan Umum",
	"Jl. Lorong Rizki Mibo",
	"Jl. Taman Kurnia Geuceu Kayee Jato",
	"Jl. Twk.Chek, Jl. Seulanga Cs Lhong Raya",
	"Jl. Tgk. Abdurrahman, Jl. Nek Ku Lam Ara",
	"Jl. Tgk Musa Dusun Panglima Nyak Raja Lamlagang",
	"Jl. Banda Jaya Lamteumen Timur (Kec. JB)",
	"Jl. Himpunan Lamteumen Barat (Kec. JB)",
	"Jl. Tengoh Lamteumen Barat (Kec. JB)",
	"Jl. Saudara Lanjutan ",
	"Jl. Bahagia",
	"Jl. Sultan Salahuddin (BitaI)",
	"Jl. Malem dagang",
	"Jl. Mahmet Ali Aydinlar Sokagi",
	"Jl. Muhittin dadalioglu Sokagi",
	"Jl. Tgk. Razali Juned",
	"Jl. Tgk. Chiek Dibitai",
	"Jl. Imuem Geh",
	"Jl. Tuan Magdum",
	"Jl. Tgk. M. Yunus Sulaiman",
	"Jl. Keuchik Musa",
	"Jl. Tgk. Djohan",
	"Jl. Tgk. M. Hasan",
	"Jl. Erdogan Bayraktar Sokagi",
	"Jl. Riza Akca Sokagi",
	"Jl. Menasah",
	"Jl. Nasruddin Rasyid (Emperom)",
	"jl. M. Amin",
	"Jl. JKB",
	"Jl. Emperom",
	"Jl. Panglima Suud 1",
	"Jl. Panglima Suud 2",
	"Lr. Cahaya",
	"Jl. Panglima Abu",
	"Jl. Cut manyak",
	"Jl. Bambu",
	"Jl. Jakalan",
	"Jl. T. Chik",
	"Jl. Jak Lele",
	"Lr. Kutaran",
	"Jln. Diana",
	"Jl. Habsyi (Deah Raya)",
	"Jl. Pocut Meurah",
	"Jl. Abdul Muthalib",
	"Jl. HM. Raden",
	"Jl. HM. Sufi",
	"Jl. Kemuning",
	"Jl. Seulanga",
	"Jl. Tanjung",
	"Jl. Anggrek",
	"Jl. Akasia",
	"Jl. Beringin",
	"Jl. Pintu Air",
	"Jl. Hananan",
	"Jl. P. Daud",
	"Jl. Buntu",
	"Lr. Flamboyan",
	"Lr. Yahya",
	"Jl. H. Ismail Ahmad",
	"Lr. Tabrani Ibrahim",
	"Lr. Rusli tanjung",
	"Jl. Utama (Peulanggahan)",
	"Jl. Setapak",
	"Jl. Pagar Mesjid",
	"Jl. Tanggul",
	"Jl. Utama Blang Perlak (Gampong Pande)",
	"Lr. Raja Siuro",
	"Lr. Raja Siuro Kiri",
	"Lr. Raja Siuro Kanan",
	"Lr. Kuta Di Blang",
	"Lr. Kuta Di Blang Kanan",
	"Lr. Krueng Ceucong",
	"Lr. Krueng Ceucong Kanan",
	"Lr. Keuchik Somat",
	"Lr. Pintu Air",
	"Lr. Lampoh Hagu",
	"Lr. Pusara",
	"Lr. Lampoh Hagu",
	"Lr. Tanggul",
	"Lr. Blang Perlak",
	"Jl. Nyak Ita (Gampong Jawa I)",
	"Jl. Nyak Keumala",
	"Jl. Nyak raden",
	"Jl. Tuan Di Banda",
	"Lr. Mak Ipok",
	"Jl. Blang Padang",
	"Jl. Puteh",
	"Jl. Tgk. Jam",
	"Jl. Raja Kuala",
	"Jl. Abasyah Raden",
	"Lr. Mantan Keuchik",
	"Lr. Lampoh Lada",
	"Jl. Blang Perlak",
	"Jl. Aparih",
	"Jl. Yusuf",
	"Jl. Yahya Dolah",
	"Jl. Abubakar - 1 (Gampong Jawa II)",
	"Jl. Abubakar - 2",
	"Jl. Ajumu Barat",
	"Jl. Abu Suid",
	"Jl. Cut Agam",
	"Jl. Pawang Hitam",
	"Jl. PW. Abu Bakar",
	"Jl. Kap. Hamid",
	"Jl. Lampoh Kuta",
	"Jl. Langgar",
	"Jl. Bakar Husin",
	"Jl. Imbran",
	"Jl. Saaman",
	"Jl. Keumamah",
	"Jl. H. Keuchik Leumiek - Jl. Tgk. Ibrahim Desa Lamseupeung (Kec. LB)",
	"Jl. Tgk. A.M. Hasan Lueng Bata (Kec. LB)",
	"Jl. Tgk. Bungong - Jl. Komplek Perum Guru Desa",
	"Jl. Keuchik Awee",
	"Jl. Pawang daud",
	"Jl.Tgk. Ibrahim",
	"Jl. Tgk. Mangga",
	"Jl. HM. Saman D (Pante Riek)",
	"Jl.T.Umar, Jl. Asam Manis, Jl.Cot Bak U Kec.Lueng Bata",
	"Jl. Tgk. M. Ishak Cs Lueng Bata",
	"Jl. Mushalla Cs / Jl. Mini Jaya Desa Batoh",
	"Jl. Tgk. Chik Lampaloh Kec. Lueng Bata",
	"Jl. Tgk. Meugat",
	"Jl. Cut Apa Main",
	"Jl. Tgk Chik Desa Bambu",
	"Jl. Tgk. Bintang",
	"Jl. Mon Nibong",
	"Jl. Ikhsan Ie Masen Kayee Adang (Kec. SK)",
	"Jl. Tgk. Dibitai Kel. Kuta Baro (Kec. SK)",
	"Jl. Prada-I Lingkar DLLAJR (Kec. SK)",
	"Jl. Beringin (Kec. SK)",
	"Jl. Kayee Adang/Min Lamgugop (Kec. SK)",
	"Jl. Akasia (Kec. SK)",
	"Jl. Tgk. Meulagu (Tibang)",
	"Jl. Utama",
	"Jl. Cabang",
	"Jl. Alue Naga",
	"Jl. Cek lah",
	"Jl. Al - Habsi (Merduati)",
	"Jl. Al - Habsi",
	"Jl. Pocut Meurah",
	"Jl. T. Nyak Sarung",
	"Jl. Keunanga I",
	"Jl. Keunanga II",
	"Jl. S. Jhohan",
	"Jl. Siti Hawa",
	"Jl. N. Raden",
	"Jl. A. Muthalib",
	"Jl. H. M. Sufi",
	"Jl. Abdussalam",
	"Jl. Tabrani",
	"Jl. Ismail Ahmad",
	"Jl. M. Yahya",
	"Jl. Kemuning",
	"Jl. Tanjung I",
	"Jl. Tanjung ",
	"Jl. Sulanga",
	"Jl. Seulanga I",
	"Jl. Akasia",
	"Jl. Anggrek",
	"Jl. Anggrek I",
	"Jl. Beringin",
	"Jl. Flamboyan",
	"Jl. Pintu air",
	"Jl. Bangka",
	"Jl. Darussalam",
	"Jl. Darussalam 3",
	"Jl. Darussalam 2",
	"Lr. Abdul Salam",
	"Jl. M. Yusuf Hasyim",
	"Lr. Hj. Siti Maryam",
	"Lr. Nyak Sabi",
	"Lr. Melati",
	"Lr. Sentosa",
	"Lr. Bangka",
	"Jl. T. Nyak Sarung",
	"Jl. Keluarga I",
	"Jl. Keluarga 2",
	"Lr. P. Ahmad",
	"Lr. Sultan Johan",
	"Lr. Senyum",
	"Lr. Keunanga I",
	"Lr. Keunanga II",
	"Lr. U8 (Jeulingke)",
	"Lr. Mesjid",
	"Jl. Apel (Lamgugop)",
	"Jl. Dusun Lamnyong",
	"Jl. Kayee Adang",
	"Jl. Komp. P. Prof. Dr. Jamaluddin",
	"Jl. Min (belakang mesjid)",
	"Jl. Putri merendam dewi",
	"Lr. Budaya A",
	"Lr. Budaya B",
	"Lr. Mutiara",
	"Lr. Kasturi",
	"Lr. TK 1",
	"Lr. TK 2",
	"Jl. TK Al-Azhar",
	"Jl. Budidaya (depan TK)",
	"Jl. Tunggai Utama",
	"Jl. Tunggai utama Lr. Ia",
	"Jl. Tunggal VII",
	"Jl. Tunggai V",
	"Jl. Min Langgugop",
	"Jl. Tunggai III",
	"Jl. Tunggai IV",
	"Jl. Syiah Kuala (Lamdingin)",
	"Jl. Seulangga",
	"Gg. Jeumpa ",
	"Jl. Bineh Blang ",
	"Jl. Tgk. Dihaji",
	"Jl. Utama",
	"Jl. Ismail",
	"Jl. Lampoh Raya",
	"Jl. Bak Hasan ",
	"Jl. Cut Saman",
	"Jl. Tgk. Di Pulo ",
	"Jl. Batee Suasa",
	"Jl. Beuransyah ",
	"Jl. Barona",
	"Jl. Nyak Johan",
	"Jl. Tgk. Di Kuta",
	"Jl. Mushalla",
	"Jl. Mushalla ",
	"Jl. Batee Ie Mon",
	"Jl. Nyak Johan ",
	"Jl. Harapan",
	"Jl. Bahagia",
	"Jl. Zainul Hasyim",
	"Jl. Tgk. Haji",
	"Jl. H. Bintang",
	"Jl. Utoh Saleh",
	"Jl. Tgk. Hanafiah",
	"Jl. Cut Raja",
	"Jl. Rajali",
	"Jl. Baru 1 (Kec. Meuraxa)",
	"Jl. Lorong T. Umar (Kec. Meuraxa)",
	"Jl. Abu Arsad (Kec. Meuraxa)",
	"Jl. Lorong Klg-2 (Kec. Meuraxa)",
	"Jl. Lorong Klg-1 (Kec. Meuraxa)",
	"Jl. Baru 2 (Kec. Meuraxa)",
	"Jl. M. Zuned-2 (Kec. Meuraxa)",
	"Jl.Bak Arom-1 (Kec. Meuraxa)",
	"Jl. Bak Arom (Kec. Meuraxa)",
	"Jl. Petai (Kec. Meuraxa)",
	"Jl. Mantri Zainun (Kec. Meuraxa)",
	"Jl. Meusara (Kec. Meuraxa)",
	"Lorong Merak (Kec. Meuraksa)",
	"Jl. GEF (Kec. Meuraxa)",
	"Jl. Haji Bintang (Kec. Meuraxa)",
	"Jl. M. Zuned-1 (Kec. Meuraxa)",
	"Jl. Meuraksani (Kec. Meuraxa)",
	"Jl. Kp. Nangka (Kec. Meuraxa)",
	"Jl. Tengku Hanafiah (Kec. Meuraxa)",
	"Jl. Tengku M. Yusup (Kec. Meuraxa)",
	"Jl. Irigasi (Kec. Meuraxa)",
	"Jl. Sekolahan (Kec. Meuraxa)",
	"Jl. Mawar 1 (Kec. Meuraxa)",
	"Jl. Mawar 2 (Kec. Meuraxa)",
	"Jl. Tengku Haji (Kec. Meuraxa)",
	"Jl. Dona (Kec. Meuraxa)",
	"Jl. Fery (Kec. Meuraxa)",
	"Jln. Rumoh Blang (Gampong. Pie)",
	"Jl. Ismail Nyak Syam",
	"Jl. Rumoh Puteh",
	"Jl. Unida",
	"Jl. Kantor Camat",
	"Jl. Keuchik Ibrahim",
	"Jl. Cot Arun 1",
	"Jl. Cot Arun 2",
	"Jl. Dipakeh",
	"Jl. Tuan Dipakeh",
	"Jl. Harapan",
	"Jl. Bilal",
	"Jl. Payalhok",
	"Jl. K. Budiman",
	"Jl. Monda",
	"Jl. Lam Pusaka",
	"Jl. Bak Cut",
	"Jl. Bak Mee",
	"Jl. Musara",
	"Jl. Bilal I",
	"Jl. Bilai III",
	"Jl. Bilai IV",
	"Jl. Bilal V",
	"Jl. Bilai II",
	"Jl. Min Ulele",
	"Lr. Utama",
	"Jl. Monda I",
	"Jl. Balee",
	"Jl. Tuan Dikandang",
	"Jl. T. Abu",
	"Jl. Syuhada",
	"Jl. Bak Kreng",
	"Jl. Kantor Lurah",
	"Jl. Elang Timur",
	"Jl. Abd. Mutalib",
	"Jl. Monda",
	"Jl. Lorong Balee",
	"Lr. Lurah",
	"Lr. Bial",
	"Lr. Bijaksana",
	"Lr. Nyak Blukeh",
	"Lr. Dipakeh",
	"Lr. Ibnu Sabil",
	"Lr. Pribadi",
	"Lr. Musyara",
	"Lr. Keluarga",
	"Lr. Mawar",
	"Lr. Kumala II",
	"lr. Tob Aye",
	"Lr. Musalla",
	"Lr. Dasar",
	"Lr. Samping Mesjid",
	"Lr. Lampuh Kaco 2",
	"Lr. Budi",
	"Lr. Mustofa",
	"Lr. Pisang",
	"Lr. Apel",
	"Lr. Kumala",
	"Lr. Sawah I",
	"Lr. Sawah II",
	"Lr. Swah III",
	"Lr. Sawah IV",
	"Jl. Ibnu Sabil",
	"Jl. T. Benu",
	"Jl. Lam Pusaka",
	"Lr. KC Adam",
	"Lr. Bak Kulu",
	"Lr. Yatim",
	"Lr. Mesjid",
	"Lr. Melati",
	"Lr. Buntu",
	"Lr. Lampoh Kaco",
	"Jl. Pendidikan (Lamjabat, Gampong Blang)",
	"Jl. Cot Aron",
	"Jl. Masjid",
	"Jl. Kupula Raya",
	"Lr. Merak",
	"Lr. Merpati I",
	"Lr. Merpati II",
	"Lr. Balam",
	"Lr. Merpati III",
	"Jl. T. Cik Cot Jambe",
	"Jl. Sari Banun",
	"Jl. Cecak",
	"Jl. Cendana 1",
	"Jl. Cendana 2",
	"Jl. Cendana 3",
	"Jl. Cendana 4",
	"Jl. Cendana 5",
	"Jl. Cendana 6",
	"Jl. Cendana 7",
	"Jl. Cendana 8",
	"Jl. Cendawa",
	"Jl. Kupula Raya",
	"Jl. Rawa Madya",
	"Jl. Rawa Madya Swasa",
	"Jl. Tambak",
	"Jl. Teri",
	"Jl. Tgk. Batee Timoh",
	"Jl. Pusara Cs.",
	"Jl. Gang Kupula",
	"Jl. Bakti AMD",
	"Jl. Batimoh",
	"Jl. Haji Usman",
	"Jl. Pang Pango",
	"Jl. Pangulee Balok",
	"Jl. Petua 1",
	"Jl. Petua 2",
	"Jl. Petua 3",
	"Jl. Petua Utama",
	"Jl. Pusara",
	"Jl. Rawa Buntu",
	"Jl. Rawa Damai",
	"Jl. Tgk. H. Syeh",
	"Jl. Bak Geuleupeue Cs.",
	"Jl. Gang Rajali",
	"Jl. Bak Geuleupe",
	"Jl. Kost",
	"Jl. T. Syarief",
}
